export const CLERK_JWT_ISSUER_DOMAIN = process.env.NEXT_CLERK_JWT_ISSUER_DOMAIN;
export const CLERK_PUBLISHABLE_KEY = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;
export const CONVEX_URL = process.env.NEXT_PUBLIC_CONVEX_URL;
export const LIVEBLOCKS_SECRET_KEY = process.env.NEXT_PUBLIC_LIVEBLOCKS_SECRET_KEY;
export const LIVEBLOCKS_PUBLIC_KEY = process.env.NEXT_PUBLIC_LIVEBLOCKS_PUBLIC_KEY;